---
  - name: update apt source list with mirrors
    copy:
      src: sources.list
      backup: yes
      dest: /etc/apt/sources.list
  - name: Check if pip is already installed
    command: pip --version
    ignore_errors: true
    changed_when: false
    register: pip_is_installed
  - name: Install pip
    apt:
      name: python3-pip
      update_cache: yes
    when: pip_is_installed.rc != 0
  - name: update pip
    shell: pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
    when: pip_is_installed.rc != 0
  - name: setup pipy mirror
    shell: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    when: pip_is_installed.rc != 0
