---
- name: check docker-ce
  shell: "docker --version"
  register: docker_version
  ignore_errors: true

- name: install docker-ce
  include: "install.yml"
  when: "'version' not in docker_version.stdout"

- name: set up docker registry mirrors
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Install docker-py
  pip:
    name: docker-py

- name: Create {{ docker_home }} directory
  file:
    path: "{{ docker_home }}"
    state: directory
