---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: ['apt-transport-https','ca-certificates','software-properties-common']
    update_cache: yes

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
  register: add_repository_key
  ignore_errors: true

- name: Alternative - Add Docker repository key
  shell: "curl -fsSL {{ apt_key_url }} | sudo apt-key add -"
  args:
    warn: no
    #when: add_repository_key | failed

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu eoan stable
    #repo: deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes

- name: set up docker registry mirrors
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Install docker-py
  pip:
    name: docker-py

- name: Create {{ docker_home }} directory
  file:
    path: "{{ docker_home }}"
    state: directory
